apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brlan-r2
spec:
  nodeSelector: 
    adetalhouet-network/lan: "site-2"
  desiredState:
    interfaces:
      - name: brlan-r2
        description: Linux bridge for LAN connectivity in Site 2
        type: linux-bridge
        state: up
        ipv4:
          enabled: true
          dhcp: true
        bridge:
          options:
            stp:
              enabled: true
          port:
            - name: enp8s0
