apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: remove-brlan
spec:
  desiredState:
    interfaces:
      - name: brlan-r1
        type: linux-bridge
        state: absent
