apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: csr1kv-qcow2
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    storageClassName: ocs-storagecluster-ceph-rbd
    resources:
      requests:
        storage: 16Gi
    volumeMode: Block
  source:
    http:
      url: >-
        https://lab-adetalhouet.s3.ca-central-1.amazonaws.com/csr1000v-universalk9.16.09.05-serial.qcow2
