apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: p2p1
spec:
  desiredState:
    interfaces:
      - name: p2p1
        description: Linux bridge p2p1
        type: linux-bridge
        state: absent
        ipv4:
          enabled: false
        bridge:
          options:
            stp:
              enabled: false
