apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: r1-to-r2
spec:
  desiredState:
    interfaces:
      - name: r1-to-r2
        description: Linux bridge r1-to-r2
        type: linux-bridge
        state: up
        ipv4:
          enabled: false
        bridge:
          options:
            stp:
              enabled: false
