apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: r2-to-r3
spec:
  desiredState:
    interfaces:
      - name: r2-to-r3
        description: Linux bridge r2-to-r3
        type: linux-bridge
        state: up
        ipv4:
          enabled: false
        bridge:
          options:
            stp:
              enabled: false
