apiVersion: v1
kind: Pod
metadata:
  name: r1-client
  annotations:
    k8s.v1.cni.cncf.io/networks: lan-r1
spec:
  nodeSelector:
    adetalhouet-network/lan: "site-1"
  containers:
  - name: example-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools