apiVersion: v1
kind: Pod
metadata:
  name: r2-client
  annotations:
    k8s.v1.cni.cncf.io/networks: lan-r2
spec:
  nodeSelector:
    adetalhouet-network/lan: "site-2"
  containers:
  - name: example-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools