kind: Service
apiVersion: v1
metadata:
  name: r2-netconf-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 22001
      targetPort: 830
  type: NodePort
  selector:
    kubevirt.io/domain: r2
