apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: remove-brint3
spec:
  desiredState:
    interfaces:
      - name: brint3-master2
        type: linux-bridge
        state: absent
