apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/brlan-r2
  name: r2
spec:
  config: >-
    {"name":"r2","cniVersion":"0.3.1","plugins":[{"type":"cnv-bridge","bridge":"brlan-r2","ipam":{}},{"type":"cnv-tuning"}]}