apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/brwan
  name: wan
spec:
  config: >-
        {"name":"wan","cniVersion":"0.3.1","plugins":[{"type":"cnv-bridge","bridge":"brwan","ipam":{}},{"type":"cnv-tuning"}]}
