apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brvlan
spec:
  desiredState:
    interfaces:
      - name: brvlan
        description: Linux bridge with enp5s0f1 as a port
        type: linux-bridge
        state: up
        ipv4:
          enabled: false
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp5s0f1
