apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: enp8s0
spec:
  desiredState:
    interfaces:
      - name: enp5s0f1
        description: attached to brvlan
        type: ethernet
        state: up

        ipv4:
          enabled: false
