apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: enp8s0
spec:
  desiredState:
    interfaces:
      - name: enp8s0
        description: attached to brint3
        type: ethernet
        state: up
        ipv4:
          enabled: false